---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ github_webhook_service_name }}'
    consul_services:
      - name: '{{ github_webhook_service_name }}'
        tags: ['{{ github_webhook_service_user }}', 'github', 'webhook']
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        checks:
          - id: '{{ github_webhook_service_name }}-health'
            name: ' {{ github_webhook_service_user }} GitHub Webhook check'
            type: 'http'
            http: 'http://localhost:{{ github_webhook_port }}/health'
